# which directories should be walked to find git repositories?
scandirs:

  # a list of one/more starting points
  # this will have env vars expanded
  include:
    - $HOME/apps

  # a list of specific directories to exclude from the scan
  # this will have env vars expanded
  exclude:
    - $GOPATH/pkg

# which files to ignore inside a git repo
# any .gitignore file in your repo will be adhered to, the config
# below allows your repo to consider files to be added but
# ignored by dirtygit
gitignore:

  fileglob:
    - go.sum
    - log
    - "*.orig"
    - "*.old"
    - "*.rpm"
    - "*.pyc"
    - .DS_Store

  dirglob:
    - vendor
    - new
    - old

# if true, walking the directory tree underneath the `include` directories
# will traverse directories pointed to be symlinks
followsymlinks: true
